from django.contrib import admin
from .models import Users
from django.contrib.auth import admin as auth_admin_django
from .forms import UserChangeForm, UserCreationForm

# Register your models here.

"""
QUERO QUE OS FORMS QUE PERSONALIZAMOS EM FORMS APAREÇAM NO ADMIN
COM OS CAMPOS ADICIONADOS

PARA REGISTRAR QUALQUER MODEL NO ADMIN E ADICIONAR ALGUMAS
CONFIGURAÇÕES.

@ADMIN.REGISTER(USERS)

MANTER O ADMIN COMO ERA ANTES MAS COM ADIÇÃO DE ALGUNS CAMPOS
ENTÃO PRECISO HERDAR DE ADMIN_AUTH_DJANGO E A CLASSE USERADMIN
PARA CADASTRAR UM USUÁRIO, ETC.

ADICIONANDO CAMPO COM FIELDSETS

USAMOS O DECORADOR @ADMIN.REGISTER PARA REGISTRAR O MODELO DE USUÁRIO PERSONALIZADO.

SUBSTITUÍMOS O USERADMIN PADRÃO PELO USERADMIN PERSONALIZADO.

ADICIONAMOS O CAMPO DE ESCOLHA DE CARGO AO USERADMIN PERSONALIZADO.

FORM = USERCHANGEFORM: SUBSTITUÍMOS O FORMULÁRIO DE ALTERAÇÃO DE USUÁRIO PADRÃO PELO FORMULÁRIO DE ALTERAÇÃO DE USUÁRIO PERSONALIZADO.

ADD_FORM = USERCREATIONFORM: SUBSTITUÍMOS O FORMULÁRIO DE CRIAÇÃO DE USUÁRIO PADRÃO PELO FORMULÁRIO DE CRIAÇÃO DE USUÁRIO PERSONALIZADO.

MODEL = USERS: SUBSTITUÍMOS O MODELO DE USUÁRIO PADRÃO PELO MODELO DE USUÁRIO PERSONALIZADO.

FIELDSETS = AUTH_ADMIN_DJANGO.USERADMIN.FIELDSETS + (('CARGO', {'FIELDS': ('CARGO',)}),): ADICIONAMOS O CAMPO DE ESCOLHA DE CARGO AO USERADMIN PERSONALIZADO.

E ADICIONAR O SEGUINTE CÓDIGO NO SETTINGS.PY:

AUTH_USER_MODEL = 'USUARIOS.USERS'

PARA ADICIONAR AO BANCO DE DADOS, EXECUTE O SEGUINTE COMANDO:

PYTHON MANAGE.PY MAKEMIGRATIONS
PYTHON MANAGE.PY MIGRATE
"""

@admin.register(Users)
class UsersAdmin(auth_admin_django.UserAdmin):
    form = UserChangeForm
    add_form = UserCreationForm
    model = Users
    fieldsets = auth_admin_django.UserAdmin.fieldsets + (
        ('Cargo', {'fields': ('cargo',)}),
    )
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('username', 'password1', 'password2', 'cargo'),
        }),
    )
